import { Employee } from "../app/models/employee.model";

export const employeesData: Employee[] = [
    {
        id: '1',
        username: 'john_doe',
        firstName: 'John',
        lastName: 'Doe',
        email: 'john.doe@example.com',
        birthDate: new Date('1990-01-01'),
        basicSalary: 50000,
        status: 'Active',
        group: 'Engineering',
        description: 'Software Engineer'
    },
    {
        id: '2',
        username: 'jane_smith',
        firstName: 'Jane',
        lastName: 'Smith',
        email: 'jane.smith@example.com',
        birthDate: new Date('1991-02-15'),
        basicSalary: 60000,
        status: 'Non-Active',
        group: 'Marketing',
        description: 'Marketing Manager'
    },
    {
        id: '3',
        username: 'michael_johnson',
        firstName: 'Michael',
        lastName: 'Johnson',
        email: 'michael.johnson@example.com',
        birthDate: new Date('1985-07-20'),
        basicSalary: 70000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Representative'
    },
    {
        id: '4',
        username: 'emily_brown',
        firstName: 'Emily',
        lastName: 'Brown',
        email: 'emily.brown@example.com',
        birthDate: new Date('1988-04-05'),
        basicSalary: 55000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Manager'
    },
    {
        id: '5',
        username: 'david_williams',
        firstName: 'David',
        lastName: 'Williams',
        email: 'david.williams@example.com',
        birthDate: new Date('1993-09-10'),
        basicSalary: 48000,
        status: 'Active',
        group: 'Engineering',
        description: 'Software Developer'
    },
    {
        id: '6',
        username: 'sarah_jones',
        firstName: 'Sarah',
        lastName: 'Jones',
        email: 'sarah.jones@example.com',
        birthDate: new Date('1992-11-30'),
        basicSalary: 52000,
        status: 'Active',
        group: 'Marketing',
        description: 'Marketing Specialist'
    },
    {
        id: '7',
        username: 'robert_white',
        firstName: 'Robert',
        lastName: 'White',
        email: 'robert.white@example.com',
        birthDate: new Date('1987-03-25'),
        basicSalary: 62000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Manager'
    },
    {
        id: '8',
        username: 'lisa_miller',
        firstName: 'Lisa',
        lastName: 'Miller',
        email: 'lisa.miller@example.com',
        birthDate: new Date('1986-06-12'),
        basicSalary: 58000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Coordinator'
    },
    {
        id: '9',
        username: 'peter_davis',
        firstName: 'Peter',
        lastName: 'Davis',
        email: 'peter.davis@example.com',
        birthDate: new Date('1989-08-18'),
        basicSalary: 53000,
        status: 'Active',
        group: 'Engineering',
        description: 'Front-end Developer'
    },
    {
        id: '10',
        username: 'jennifer_clark',
        firstName: 'Jennifer',
        lastName: 'Clark',
        email: 'jennifer.clark@example.com',
        birthDate: new Date('1994-12-07'),
        basicSalary: 57000,
        status: 'Active',
        group: 'Marketing',
        description: 'Content Writer'
    },
    {
        id: '11',
        username: 'william_thomas',
        firstName: 'William',
        lastName: 'Thomas',
        email: 'william.thomas@example.com',
        birthDate: new Date('1984-02-28'),
        basicSalary: 64000,
        status: 'Active',
        group: 'Sales',
        description: 'Business Development Manager'
    },
    {
        id: '12',
        username: 'amanda_scott',
        firstName: 'Amanda',
        lastName: 'Scott',
        email: 'amanda.scott@example.com',
        birthDate: new Date('1990-05-14'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'HR Manager'
    },
    {
        id: '13',
        username: 'matthew_hall',
        firstName: 'Matthew',
        lastName: 'Hall',
        email: 'matthew.hall@example.com',
        birthDate: new Date('1991-07-19'),
        basicSalary: 51000,
        status: 'Active',
        group: 'Engineering',
        description: 'Backend Developer'
    },
    {
        id: '14',
        username: 'laura_martin',
        firstName: 'Laura',
        lastName: 'Martin',
        email: 'laura.martin@example.com',
        birthDate: new Date('1988-09-22'),
        basicSalary: 55000,
        status: 'Active',
        group: 'Marketing',
        description: 'Social Media Specialist'
    },
    {
        id: '15',
        username: 'kevin_adams',
        firstName: 'Kevin',
        lastName: 'Adams',
        email: 'kevin.adams@example.com',
        birthDate: new Date('1986-11-11'),
        basicSalary: 56000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Executive'
    },
    {
        id: '16',
        username: 'melissa_wilson',
        firstName: 'Melissa',
        lastName: 'Wilson',
        email: 'melissa.wilson@example.com',
        birthDate: new Date('1993-01-25'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Analyst'
    },
    {
        id: '17',
        username: 'steven_robinson',
        firstName: 'Steven',
        lastName: 'Robinson',
        email: 'steven.robinson@example.com',
        birthDate: new Date('1985-03-17'),
        basicSalary: 49000,
        status: 'Active',
        group: 'Engineering',
        description: 'DevOps Engineer'
    },
    {
        id: '18',
        username: 'christina_thompson',
        firstName: 'Christina',
        lastName: 'Thompson',
        email: 'christina.thompson@example.com',
        birthDate: new Date('1992-06-30'),
        basicSalary: 58000,
        status: 'Active',
        group: 'Marketing',
        description: 'Graphic Designer'
    },
    {
        id: '19',
        username: 'george_carter',
        firstName: 'George',
        lastName: 'Carter',
        email: 'george.carter@example.com',
        birthDate: new Date('1989-08-05'),
        basicSalary: 51000,
        status: 'Active',
        group: 'Sales',
        description: 'Customer Service Manager'
    },
    {
        id: '20',
        username: 'stephanie_evans',
        firstName: 'Stephanie',
        lastName: 'Evans',
        email: 'stephanie.evans@example.com',
        birthDate: new Date('1987-10-12'),
        basicSalary: 53000,
        status: 'Active',
        group: 'Operations',
        description: 'Supply Chain Coordinator'
    },
    {
        id: '21',
        username: 'patrick_morris',
        firstName: 'Patrick',
        lastName: 'Morris',
        email: 'patrick.morris@example.com',
        birthDate: new Date('1990-12-15'),
        basicSalary: 54000,
        status: 'Active',
        group: 'Engineering',
        description: 'Systems Analyst'
    },
    {
        id: '22',
        username: 'rachel_ward',
        firstName: 'Rachel',
        lastName: 'Ward',
        email: 'rachel.ward@example.com',
        birthDate: new Date('1986-02-28'),
        basicSalary: 57000,
        status: 'Active',
        group: 'Marketing',
        description: 'SEO Specialist'
    },
    {
        id: '23',
        username: 'eric_roberts',
        firstName: 'Eric',
        lastName: 'Roberts',
        email: 'eric.roberts@example.com',
        birthDate: new Date('1993-04-10'),
        basicSalary: 52000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Analyst'
    },
    {
        id: '24',
        username: 'samantha_wood',
        firstName: 'Samantha',
        lastName: 'Wood',
        email: 'samantha.wood@example.com',
        birthDate: new Date('1988-06-05'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Financial Analyst'
    },
    {
        id: '25',
        username: 'daniel_cook',
        firstName: 'Daniel',
        lastName: 'Cook',
        email: 'daniel.cook@example.com',
        birthDate: new Date('1985-08-20'),
        basicSalary: 48000,
        status: 'Active',
        group: 'Engineering',
        description: 'Full Stack Developer'
    },
    {
        id: '26',
        username: 'ashley_bailey',
        firstName: 'Ashley',
        lastName: 'Bailey',
        email: 'ashley.bailey@example.com',
        birthDate: new Date('1992-10-15'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Marketing',
        description: 'Content Marketing Manager'
    },
    {
        id: '27',
        username: 'ryan_howard',
        firstName: 'Ryan',
        lastName: 'Howard',
        email: 'ryan.howard@example.com',
        birthDate: new Date('1987-12-10'),
        basicSalary: 65000,
        status: 'Active',
        group: 'Sales',
        description: 'Key Account Manager'
    },
    {
        id: '28',
        username: 'jessica_richardson',
        firstName: 'Jessica',
        lastName: 'Richardson',
        email: 'jessica.richardson@example.com',
        birthDate: new Date('1986-03-25'),
        basicSalary: 58000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Supervisor'
    },
    {
        id: '29',
        username: 'justin_russell',
        firstName: 'Justin',
        lastName: 'Russell',
        email: 'justin.russell@example.com',
        birthDate: new Date('1991-05-18'),
        basicSalary: 55000,
        status: 'Active',
        group: 'Engineering',
        description: 'Software Architect'
    },
    {
        id: '30',
        username: 'amanda_young',
        firstName: 'Amanda',
        lastName: 'Young',
        email: 'amanda.young@example.com',
        birthDate: new Date('1989-07-22'),
        basicSalary: 52000,
        status: 'Active',
        group: 'Marketing',
        description: 'UX/UI Designer'
    },
    {
        id: '31',
        username: 'brandon_king',
        firstName: 'Brandon',
        lastName: 'King',
        email: 'brandon.king@example.com',
        birthDate: new Date('1994-09-15'),
        basicSalary: 49000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Coordinator'
    },
    {
        id: '32',
        username: 'natalie_scott',
        firstName: 'Natalie',
        lastName: 'Scott',
        email: 'natalie.scott@example.com',
        birthDate: new Date('1984-11-10'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Operations',
        description: 'Quality Assurance Manager'
    },
    {
        id: '33',
        username: 'alexander_green',
        firstName: 'Alexander',
        lastName: 'Green',
        email: 'alexander.green@example.com',
        birthDate: new Date('1990-01-05'),
        basicSalary: 58000,
        status: 'Active',
        group: 'Engineering',
        description: 'Network Engineer'
    },
    {
        id: '34',
        username: 'kelly_hall',
        firstName: 'Kelly',
        lastName: 'Hall',
        email: 'kelly.hall@example.com',
        birthDate: new Date('1987-02-28'),
        basicSalary: 55000,
        status: 'Active',
        group: 'Marketing',
        description: 'Digital Marketing Specialist'
    },
    {
        id: '35',
        username: 'matthew_adams',
        firstName: 'Matthew',
        lastName: 'Adams',
        email: 'matthew.adams@example.com',
        birthDate: new Date('1992-04-15'),
        basicSalary: 51000,
        status: 'Active',
        group: 'Sales',
        description: 'Business Analyst'
    },
    {
        id: '36',
        username: 'jessica_thomas',
        firstName: 'Jessica',
        lastName: 'Thomas',
        email: 'jessica.thomas@example.com',
        birthDate: new Date('1988-06-18'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Planner'
    },
    {
        id: '37',
        username: 'nathan_cook',
        firstName: 'Nathan',
        lastName: 'Cook',
        email: 'nathan.cook@example.com',
        birthDate: new Date('1985-08-25'),
        basicSalary: 48000,
        status: 'Active',
        group: 'Engineering',
        description: 'Backend Developer'
    },
    {
        id: '38',
        username: 'ashley_rogers',
        firstName: 'Ashley',
        lastName: 'Rogers',
        email: 'ashley.rogers@example.com',
        birthDate: new Date('1991-10-30'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Marketing',
        description: 'Content Creator'
    },
    {
        id: '39',
        username: 'ryan_ross',
        firstName: 'Ryan',
        lastName: 'Ross',
        email: 'ryan.ross@example.com',
        birthDate: new Date('1986-12-12'),
        basicSalary: 65000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Consultant'
    },
    {
        id: '40',
        username: 'sarah_bell',
        firstName: 'Sarah',
        lastName: 'Bell',
        email: 'sarah.bell@example.com',
        birthDate: new Date('1993-03-25'),
        basicSalary: 62000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Specialist'
    },
    {
        id: '41',
        username: 'jacob_howard',
        firstName: 'Jacob',
        lastName: 'Howard',
        email: 'jacob.howard@example.com',
        birthDate: new Date('1984-05-18'),
        basicSalary: 54000,
        status: 'Active',
        group: 'Engineering',
        description: 'Data Scientist'
    },
    {
        id: '42',
        username: 'olivia_wright',
        firstName: 'Olivia',
        lastName: 'Wright',
        email: 'olivia.wright@example.com',
        birthDate: new Date('1989-07-22'),
        basicSalary: 52000,
        status: 'Active',
        group: 'Marketing',
        description: 'Brand Manager'
    },
    {
        id: '43',
        username: 'adam_baker',
        firstName: 'Adam',
        lastName: 'Baker',
        email: 'adam.baker@example.com',
        birthDate: new Date('1994-09-15'),
        basicSalary: 49000,
        status: 'Active',
        group: 'Sales',
        description: 'Customer Success Manager'
    },
    {
        id: '44',
        username: 'victoria_king',
        firstName: 'Victoria',
        lastName: 'King',
        email: 'victoria.king@example.com',
        birthDate: new Date('1986-11-10'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Operations',
        description: 'Logistics Manager'
    },
    {
        id: '45',
        username: 'eric_mitchell',
        firstName: 'Eric',
        lastName: 'Mitchell',
        email: 'eric.mitchell@example.com',
        birthDate: new Date('1990-01-05'),
        basicSalary: 58000,
        status: 'Active',
        group: 'Engineering',
        description: 'Security Analyst'
    },
    {
        id: '46',
        username: 'sophia_scott',
        firstName: 'Sophia',
        lastName: 'Scott',
        email: 'sophia.scott@example.com',
        birthDate: new Date('1987-02-28'),
        basicSalary: 55000,
        status: 'Active',
        group: 'Marketing',
        description: 'SEO Manager'
    },
    {
        id: '47',
        username: 'james_hill',
        firstName: 'James',
        lastName: 'Hill',
        email: 'james.hill@example.com',
        birthDate: new Date('1992-04-15'),
        basicSalary: 51000,
        status: 'Active',
        group: 'Sales',
        description: 'Account Manager'
    },
    {
        id: '48',
        username: 'emma_young',
        firstName: 'Emma',
        lastName: 'Young',
        email: 'emma.young@example.com',
        birthDate: new Date('1988-06-18'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Financial Controller'
    },
    {
        id: '49',
        username: 'luke_lewis',
        firstName: 'Luke',
        lastName: 'Lewis',
        email: 'luke.lewis@example.com',
        birthDate: new Date('1985-08-25'),
        basicSalary: 48000,
        status: 'Active',
        group: 'Engineering',
        description: 'Cloud Solutions Architect'
    },
    {
        id: '50',
        username: 'natalie_edwards',
        firstName: 'Natalie',
        lastName: 'Edwards',
        email: 'natalie.edwards@example.com',
        birthDate: new Date('1991-10-30'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Marketing',
        description: 'Brand Strategist'
    },
    {
        id: '51',
        username: 'jacob_harris',
        firstName: 'Jacob',
        lastName: 'Harris',
        email: 'jacob.harris@example.com',
        birthDate: new Date('1986-12-12'),
        basicSalary: 65000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Director'
    },
    {
        id: '52',
        username: 'olivia_clark',
        firstName: 'Olivia',
        lastName: 'Clark',
        email: 'olivia.clark@example.com',
        birthDate: new Date('1993-03-25'),
        basicSalary: 62000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Manager'
    },
    {
        id: '53',
        username: 'ethan_bell',
        firstName: 'Ethan',
        lastName: 'Bell',
        email: 'ethan.bell@example.com',
        birthDate: new Date('1984-05-18'),
        basicSalary: 54000,
        status: 'Active',
        group: 'Engineering',
        description: 'Software Engineer'
    },
    {
        id: '54',
        username: 'isabella_gonzalez',
        firstName: 'Isabella',
        lastName: 'Gonzalez',
        email: 'isabella.gonzalez@example.com',
        birthDate: new Date('1989-07-22'),
        basicSalary: 52000,
        status: 'Active',
        group: 'Marketing',
        description: 'Content Manager'
    },
    {
        id: '55',
        username: 'noah_robertson',
        firstName: 'Noah',
        lastName: 'Robertson',
        email: 'noah.robertson@example.com',
        birthDate: new Date('1994-09-15'),
        basicSalary: 49000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Representative'
    },
    {
        id: '56',
        username: 'amelia_rodriguez',
        firstName: 'Amelia',
        lastName: 'Rodriguez',
        email: 'amelia.rodriguez@example.com',
        birthDate: new Date('1986-11-10'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Analyst'
    },
    {
        id: '57',
        username: 'jacob_king',
        firstName: 'Jacob',
        lastName: 'King',
        email: 'jacob.king@example.com',
        birthDate: new Date('1990-01-05'),
        basicSalary: 58000,
        status: 'Active',
        group: 'Engineering',
        description: 'Systems Engineer'
    },
    {
        id: '58',
        username: 'olivia_martinez',
        firstName: 'Olivia',
        lastName: 'Martinez',
        email: 'olivia.martinez@example.com',
        birthDate: new Date('1987-02-28'),
        basicSalary: 55000,
        status: 'Active',
        group: 'Marketing',
        description: 'Social Media Manager'
    },
    {
        id: '59',
        username: 'william_hernandez',
        firstName: 'William',
        lastName: 'Hernandez',
        email: 'william.hernandez@example.com',
        birthDate: new Date('1992-04-15'),
        basicSalary: 51000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Executive'
    },
    {
        id: '60',
        username: 'emily_nelson',
        firstName: 'Emily',
        lastName: 'Nelson',
        email: 'emily.nelson@example.com',
        birthDate: new Date('1988-06-18'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Financial Analyst'
    },
    {
        id: '61',
        username: 'daniel_garcia',
        firstName: 'Daniel',
        lastName: 'Garcia',
        email: 'daniel.garcia@example.com',
        birthDate: new Date('1985-08-25'),
        basicSalary: 48000,
        status: 'Active',
        group: 'Engineering',
        description: 'Full Stack Developer'
    },
    {
        id: '62',
        username: 'mia_morris',
        firstName: 'Mia',
        lastName: 'Morris',
        email: 'mia.morris@example.com',
        birthDate: new Date('1991-10-30'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Marketing',
        description: 'Copywriter'
    },
    {
        id: '63',
        username: 'logan_perez',
        firstName: 'Logan',
        lastName: 'Perez',
        email: 'logan.perez@example.com',
        birthDate: new Date('1986-12-12'),
        basicSalary: 65000,
        status: 'Active',
        group: 'Sales',
        description: 'Business Development Manager'
    },
    {
        id: '64',
        username: 'olivia_taylor',
        firstName: 'Olivia',
        lastName: 'Taylor',
        email: 'olivia.taylor@example.com',
        birthDate: new Date('1993-03-25'),
        basicSalary: 62000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Manager'
    },
    {
        id: '65',
        username: 'ethan_james',
        firstName: 'Ethan',
        lastName: 'James',
        email: 'ethan.james@example.com',
        birthDate: new Date('1984-05-18'),
        basicSalary: 54000,
        status: 'Active',
        group: 'Engineering',
        description: 'Software Engineer'
    },
    {
        id: '66',
        username: 'isabella_morgan',
        firstName: 'Isabella',
        lastName: 'Morgan',
        email: 'isabella.morgan@example.com',
        birthDate: new Date('1989-07-22'),
        basicSalary: 52000,
        status: 'Active',
        group: 'Marketing',
        description: 'Digital Marketing Manager'
    },
    {
        id: '67',
        username: 'noah_diaz',
        firstName: 'Noah',
        lastName: 'Diaz',
        email: 'noah.diaz@example.com',
        birthDate: new Date('1994-09-15'),
        basicSalary: 49000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Consultant'
    },
    {
        id: '68',
        username: 'amelia_roberts',
        firstName: 'Amelia',
        lastName: 'Roberts',
        email: 'amelia.roberts@example.com',
        birthDate: new Date('1986-11-10'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Analyst'
    },
    {
        id: '69',
        username: 'jacob_walker',
        firstName: 'Jacob',
        lastName: 'Walker',
        email: 'jacob.walker@example.com',
        birthDate: new Date('1990-01-05'),
        basicSalary: 58000,
        status: 'Active',
        group: 'Engineering',
        description: 'Network Engineer'
    },
    {
        id: '70',
        username: 'olivia_anderson',
        firstName: 'Olivia',
        lastName: 'Anderson',
        email: 'olivia.anderson@example.com',
        birthDate: new Date('1987-02-28'),
        basicSalary: 55000,
        status: 'Active',
        group: 'Marketing',
        description: 'Content Creator'
    },
    {
        id: '71',
        username: 'william_wilson',
        firstName: 'William',
        lastName: 'Wilson',
        email: 'william.wilson@example.com',
        birthDate: new Date('1992-04-15'),
        basicSalary: 51000,
        status: 'Active',
        group: 'Sales',
        description: 'Account Manager'
    },
    {
        id: '72',
        username: 'emma_martinez',
        firstName: 'Emma',
        lastName: 'Martinez',
        email: 'emma.martinez@example.com',
        birthDate: new Date('1988-06-18'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Financial Analyst'
    },
    {
        id: '73',
        username: 'luke_lopez',
        firstName: 'Luke',
        lastName: 'Lopez',
        email: 'luke.lopez@example.com',
        birthDate: new Date('1985-08-25'),
        basicSalary: 48000,
        status: 'Active',
        group: 'Engineering',
        description: 'Backend Developer'
    },
    {
        id: '74',
        username: 'natalie_king',
        firstName: 'Natalie',
        lastName: 'King',
        email: 'natalie.king@example.com',
        birthDate: new Date('1991-10-30'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Marketing',
        description: 'UX/UI Designer'
    },
    {
        id: '75',
        username: 'jacob_carter',
        firstName: 'Jacob',
        lastName: 'Carter',
        email: 'jacob.carter@example.com',
        birthDate: new Date('1986-12-12'),
        basicSalary: 65000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Manager'
    },
    {
        id: '76',
        username: 'olivia_gomez',
        firstName: 'Olivia',
        lastName: 'Gomez',
        email: 'olivia.gomez@example.com',
        birthDate: new Date('1993-03-25'),
        basicSalary: 62000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Manager'
    },
    {
        id: '77',
        username: 'ethan_richardson',
        firstName: 'Ethan',
        lastName: 'Richardson',
        email: 'ethan.richardson@example.com',
        birthDate: new Date('1984-05-18'),
        basicSalary: 54000,
        status: 'Active',
        group: 'Engineering',
        description: 'DevOps Engineer'
    },
    {
        id: '78',
        username: 'isabella_scott',
        firstName: 'Isabella',
        lastName: 'Scott',
        email: 'isabella.scott@example.com',
        birthDate: new Date('1989-07-22'),
        basicSalary: 52000,
        status: 'Active',
        group: 'Marketing',
        description: 'Social Media Specialist'
    },
    {
        id: '79',
        username: 'noah_young',
        firstName: 'Noah',
        lastName: 'Young',
        email: 'noah.young@example.com',
        birthDate: new Date('1994-09-15'),
        basicSalary: 49000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Representative'
    },
    {
        id: '80',
        username: 'amelia_morris',
        firstName: 'Amelia',
        lastName: 'Morris',
        email: 'amelia.morris@example.com',
        birthDate: new Date('1986-11-10'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Operations',
        description: 'Logistics Coordinator'
    },
    {
        id: '81',
        username: 'jacob_hill',
        firstName: 'Jacob',
        lastName: 'Hill',
        email: 'jacob.hill@example.com',
        birthDate: new Date('1990-01-05'),
        basicSalary: 58000,
        status: 'Active',
        group: 'Engineering',
        description: 'Systems Administrator'
    },
    {
        id: '82',
        username: 'olivia_garcia',
        firstName: 'Olivia',
        lastName: 'Garcia',
        email: 'olivia.garcia@example.com',
        birthDate: new Date('1987-02-28'),
        basicSalary: 55000,
        status: 'Active',
        group: 'Marketing',
        description: 'Content Strategist'
    },
    {
        id: '83',
        username: 'william_martinez',
        firstName: 'William',
        lastName: 'Martinez',
        email: 'william.martinez@example.com',
        birthDate: new Date('1992-04-15'),
        basicSalary: 51000,
        status: 'Active',
        group: 'Sales',
        description: 'Business Analyst'
    },
    {
        id: '84',
        username: 'emma_lewis',
        firstName: 'Emma',
        lastName: 'Lewis',
        email: 'emma.lewis@example.com',
        birthDate: new Date('1988-06-18'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Manager'
    },
    {
        id: '85',
        username: 'luke_nelson',
        firstName: 'Luke',
        lastName: 'Nelson',
        email: 'luke.nelson@example.com',
        birthDate: new Date('1985-08-25'),
        basicSalary: 48000,
        status: 'Active',
        group: 'Engineering',
        description: 'Frontend Developer'
    },
    {
        id: '86',
        username: 'natalie_roberts',
        firstName: 'Natalie',
        lastName: 'Roberts',
        email: 'natalie.roberts@example.com',
        birthDate: new Date('1991-10-30'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Marketing',
        description: 'Marketing Manager'
    },
    {
        id: '87',
        username: 'jacob_king',
        firstName: 'Jacob',
        lastName: 'King',
        email: 'jacob.king@example.com',
        birthDate: new Date('1986-12-12'),
        basicSalary: 65000,
        status: 'Active',
        group: 'Sales',
        description: 'Senior Sales Executive'
    },
    {
        id: '88',
        username: 'olivia_kelly',
        firstName: 'Olivia',
        lastName: 'Kelly',
        email: 'olivia.kelly@example.com',
        birthDate: new Date('1993-03-25'),
        basicSalary: 62000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Coordinator'
    },
    {
        id: '89',
        username: 'ethan_cook',
        firstName: 'Ethan',
        lastName: 'Cook',
        email: 'ethan.cook@example.com',
        birthDate: new Date('1984-05-18'),
        basicSalary: 54000,
        status: 'Active',
        group: 'Engineering',
        description: 'Cloud Engineer'
    },
    {
        id: '90',
        username: 'isabella_richardson',
        firstName: 'Isabella',
        lastName: 'Richardson',
        email: 'isabella.richardson@example.com',
        birthDate: new Date('1989-07-22'),
        basicSalary: 52000,
        status: 'Active',
        group: 'Marketing',
        description: 'SEO Specialist'
    },
    {
        id: '91',
        username: 'noah_ross',
        firstName: 'Noah',
        lastName: 'Ross',
        email: 'noah.ross@example.com',
        birthDate: new Date('1994-09-15'),
        basicSalary: 49000,
        status: 'Active',
        group: 'Sales',
        description: 'Account Executive'
    },
    {
        id: '92',
        username: 'amelia_carter',
        firstName: 'Amelia',
        lastName: 'Carter',
        email: 'amelia.carter@example.com',
        birthDate: new Date('1986-11-10'),
        basicSalary: 60000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Specialist'
    },
    {
        id: '93',
        username: 'jacob_gomez',
        firstName: 'Jacob',
        lastName: 'Gomez',
        email: 'jacob.gomez@example.com',
        birthDate: new Date('1990-01-05'),
        basicSalary: 58000,
        status: 'Active',
        group: 'Engineering',
        description: 'Software Developer'
    },
    {
        id: '94',
        username: 'olivia_hernandez',
        firstName: 'Olivia',
        lastName: 'Hernandez',
        email: 'olivia.hernandez@example.com',
        birthDate: new Date('1987-02-28'),
        basicSalary: 55000,
        status: 'Active',
        group: 'Marketing',
        description: 'Brand Specialist'
    },
    {
        id: '95',
        username: 'william_morgan',
        firstName: 'William',
        lastName: 'Morgan',
        email: 'william.morgan@example.com',
        birthDate: new Date('1992-04-15'),
        basicSalary: 51000,
        status: 'Active',
        group: 'Sales',
        description: 'Sales Analyst'
    },
    {
        id: '96',
        username: 'emma_scott',
        firstName: 'Emma',
        lastName: 'Scott',
        email: 'emma.scott@example.com',
        birthDate: new Date('1988-06-18'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Coordinator'
    },    
    {
        id: '97',
        username: 'emma_scott',
        firstName: 'Emma',
        lastName: 'Scott',
        email: 'emma.scott@example.com',
        birthDate: new Date('1988-06-18'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Coordinator'
    },    
    {
        id: '98',
        username: 'emma_scott',
        firstName: 'Emma',
        lastName: 'Scott',
        email: 'emma.scott@example.com',
        birthDate: new Date('1988-06-18'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Coordinator'
    },    
    {
        id: '99',
        username: 'emma_scott',
        firstName: 'Emma',
        lastName: 'Scott',
        email: 'emma.scott@example.com',
        birthDate: new Date('1988-06-18'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Coordinator'
    },    
    {
        id: '100',
        username: 'emma_scott',
        firstName: 'Emma',
        lastName: 'Scott',
        email: 'emma.scott@example.com',
        birthDate: new Date('1988-06-18'),
        basicSalary: 59000,
        status: 'Active',
        group: 'Operations',
        description: 'Operations Coordinator'
    },    
];