name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use the version of Node.js you prefer

    - name: Install dependencies
      run: npm install

    - name: Build the Angular project
      run: npm run build -- --output-path=dist --base-href=/your-repo-name/  # Ensure base-href is set correctly

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./dist
        cname: your-custom-domain.com  # Optional: If you are using a custom domain
